### PR TITLE
QRS-48, Fix the prod build

### PR DESCRIPTION
**Pull request by VitalInnovator**

### CODE REVIEW

**Comment by roszcz** [comment]
@VitalInnovator here's what I'm getting on a fresh run when I try to see the dashboard:

image

I'm running this:

```
DATA_PROBLEM=ecg_classification docker compose -f docker-compose-prd.yml build
DATA_PROBLEM=ecg_classification docker compose -f docker-compose-prd.yml up
```

**Comment by VitalInnovator** [comment]
> @VitalInnovator here's what I'm getting on a fresh run when I try to see the dashboard:

I'm working on it

**Comment by VitalInnovator** [comment]
It's a very strange error that manifests only after the project has been built. It's related to the html-midi-player. Despite the fact that you explicitly specify another DATA PROBLEM, the builder should still build all files, including those responsible for MIDI. To be honest, it's the first time I've seen such an error related to the compiler's work. I continue working on its solution.

**Comment by roszcz** [comment]
Do you know what the actual issue is? I thought the html player is a rather straightforward html/js piece of code so I'm surprised to see it causing unsolvable problems - can you elaborate a bit about what's actually going wrong here?

**Comment by VitalInnovator** [comment]
it seems more like a conflict of the player with the SWC compiler that we use to transform our Next.js (ts) code into a regular js script. During the compilation, the compiler redeclares the Identifier which was previously used.

**Comment by VitalInnovator** [comment]
Fixed

**Comment by VitalInnovator** [comment]
I managed to solve this problem by forgoing the usual package addition through npm (package manager) and adding it directly via CDN. I also had to restrict SSR for this component.

**Pull request closed without merging**
