### PR TITLE
QRS- 41, Fix records access by dataset name and Zoom view delay

### PR DESCRIPTION
**Pull request by VitalInnovator**
Fixed access to data by dataset name on the dashboard page.
I added a loading indicator. When switching to Zoom view, we wait for a response from the API /data endpoint. Sometimes this takes longer if we haven't finished loading the other charts

### CODE REVIEW

**Comment by roszcz** [comment]
Loader is cool, but I think it's not addressing to underlying design issue - if the first signal already has the data loaded, what's the point of waiting for others to load? We should show the zoom in version of the first signal, and keep waiting for the rest of the data. Here's what I recorded on staging demonstrating the issue:

https://github.com/Nospoko/data-quality-platform/assets/8056825/134c3e24-521c-4e77-a711-8ed7aa66b8f3

If I understand this PR, it will take just as long to show the first signal in zoom, but I'll see the loader while waiting? If that's the case we should rethink the approach.

Also, I don't understand what "Fix records access by dataset name" is about? There's no ticket connected describing the problem 😞 and I don't remember any details about it ...

**Comment by VitalInnovator** [comment]
I apologize for not formulating the description clearly enough. `Fix records access by dataset name` was related to our discussion at https://github.com/Nospoko/data-quality-platform/pull/19#issuecomment-1684111535. I added filtering of displayed records according to the selected dataset name on the dashboard page. Previously, the selection of a card from the dashboard did not affect anything.

**Comment by VitalInnovator** [comment]
> which one is the "unwanted data loading"? I'm involved in multiple projects and without a ticket number it's not possible for me to keep track of this and guess what you mean - if this is about the slow loader, please keep the discussion in github PR, if it's about something else, please reference a jira ticket or create one if it doesn't exist

This is about this PR comment. I've fixed it

**Review by roszcz — APPROVED** [review]

**Comment by roszcz** [comment]
> This is about this PR comment. I've fixed it

The issue I was asking about was this:

> If I understand this PR, it will take just as long to show the first signal in zoom, but I'll see the loader while waiting? If that's the case we should rethink the approach.

After deploying this PR on staging, exactly what I described seems to be the case:

https://github.com/Nospoko/data-quality-platform/assets/8056825/366b9ed8-25eb-4ce0-842f-8d8747084305

@VitalInnovator Can you please review my comments? Am I missing something here?

**Pull request merged**
