### PR TITLE
QRS-36, add DATA_PROBLEM check

### PR DESCRIPTION
**Pull request by VitalInnovator**
I've adde sh script to check DATA_PROBLEM. and update docker files
to run app use 
```sh
$ DATA_PROBLEM=ecg_classification docker compose up
```
I think you will need to make changes to the deployment and add the `DATA_PROBLEM` variable.

### CODE REVIEW

**Comment by roszcz** [comment]
@VitalInnovator I meant something different than adding an if statement - I updated the task description, let me know if it makes sense.

**Comment by VitalInnovator** [comment]
> @VitalInnovator I meant something different than adding an if statement - I updated the task description, let me know if it makes sense.

I looked at the updated task. As we discussed earlier, all the code and structure will be the same; only the chart/midi player and feedback will differ. To avoid having to duplicate all components with any design changes, I don't want to globally split next project into two different folders. Instead, we will optionally render the components we need depending on the environment variable.

As for the database, I think it makes sense to use different schemas. This will make it easier to work locally and easily switch between databases  by simply changing the database schema. What do you think about this?

**Comment by roszcz** [comment]
What I'm missing here, is the JS code is checking the `DATA_PROBLEM` variable to decide what to show. I wish for this PR to already provide the required logic, so I would expect some kind of 

```
if DATA_PROBLEM === "ecg_classification":
  data_display_element = ecg_chart
```

So when we start working on MIDI, the only change will be:

```
if DATA_PROBLEM === "ecg_classification":
  data_display_element = ecg_chart

if DATA_PROBLEM === "midi_review":
  data_display_element = midi_player
```

I think we don't have to worry about the data communication and this stage, but it's safe to assume that we will need to create multiple versions of the "data_checks" table, one for each data problem.

**Comment by VitalInnovator** [comment]
@roszcz Regarding the check of variable in the JS code, I've left this step until the point when we have alternative components. As I mentioned in the message in Discord, I've started working on adding a rating component.

But I will add `DATA_PROBLEM` check to app level.

I would prefer to keep one version of the `data_checks` but add two new fields, `score_1` and `score_2`, to it. This will help to avoid unnecessary complications of the relationships between tables.

**Comment by roszcz** [comment]
> @roszcz Regarding the check of variable in the JS code, I've left this step until the point when we have alternative components. 

The point of this task was to do this now, so we can review the approach.

If you need a second task for this, you can use exactly the same data, but call it "ecg_rating" and  switch ✅ / ❌  to something else. But I'd prefer it to be a separate PR.

**Comment by roszcz** [comment]
> I would prefer to keep one version of the data_checks but add two new fields, score_1 and score_2, to it. This will help to avoid unnecessary complications of the relationships between tables.

I think that's fine 👍 We can probably assume that there will be no switching between different data problems for every instance of this app.

**Pull request closed without merging**
