### PR TITLE
QRS-18: App flow definition

### PR DESCRIPTION
**Pull request by roszcz**
1. Improve the docker compose startup process. Everything await the database to be ready. And start's in the order `web` (created tables) -> `data` (populates tables)
2. Introduces a new way of getting data from the python api, using `position` and `exam_uid`: `GET data/?exam_uid={EXAM_UID}&position={POSITION}`
3. I did some ugly changes to the migration files to get the effect I wanted. For the next steps I think we should:
  a. Remove all existing migration files
  b. Create new migrations with the assumption that the web app has to create all the tables and fully control the schema.
4. To use the new API changes to the JS code are required.
5. I also added a couple of information about every fragment displayed at the top of each plot, which is very useful (feel free to refactor this into nicer React).

@VitalInnovator Can you take over this PR (after you're done with #10)? 
To run this locally, you will need to add `HF_TOKEN` env variable, to get it you have to set up an account on [HuggingFace](https://huggingface.co/) - let me know your username and I'll add access.

### CODE REVIEW

**Comment by VitalInnovator** [comment]
> 1. Improve the docker compose startup process. Everything await the database to be ready. And start's in the order `web` (created tables) -> `data` (populates tables)
> 2. Introduces a new way of getting data from the python api, using `position` and `exam_uid`: `GET data/?exam_uid={EXAM_UID}&position={POSITION}`
> 3. I did some ugly changes to the migration files to get the effect I wanted. For the next steps I think we should:
>    a. Remove all existing migration files
>    b. Create new migrations with the assumption that the web app has to create all the tables and fully control the schema.
> 4. To use the new API changes to the JS code are required.
> 5. I also added a couple of information about every fragment displayed at the top of each plot, which is very useful (feel free to refactor this into nicer React).
> 
> @VitalInnovator Can you take over this PR (after you're done with #10)? To run this locally, you will need to add `HF_TOKEN` env variable, to get it you have to set up an account on [HuggingFace](https://huggingface.co/) - let me know your username and I'll add access.

@roszcz I'll handle this task. It's good news that we've changed the loading order. I encountered this problem just yesterday. I had to recreate the database and had issues applying migrations. I had about 1k records left in the DB and I couldn't retrieve some of them because Python couldn't handle records with large indexes. 
My HuggingFace is  **VitaliiDom**

**Comment by roszcz** [comment]
@VitalInnovator For issues like that I recommend hard-deleting the database with `rm -r tmp/db_data`. It's also good to see if the project will start up correctly from scratch :)

**Comment by VitalInnovator** [comment]
That's exactly what I did))

**Comment by VitalInnovator** [comment]
@roszcz I'm having trouble with the `roszcz/qrs-review-v0` dataset. I received an email that access was granted, but I haven't been able to find this dataset. Therefore, I used the old one for testing. Over the weekend, I also nearly finished filtering data by exem_uuid. I will be waiting for you to merge this PR, to test with the correct dataset and get the correct commit history.

**Pull request merged**
