### PR TITLE
QRS-37, add dataset selector to the History page

### PR DESCRIPTION
**Pull request by VitalInnovator**

### CODE REVIEW

**Comment by roszcz** [comment]
When reviewing data on this branch, something changes in the chart element after first review sample, and the ✅ / ❌  no longer work:

https://github.com/Nospoko/data-quality-platform/assets/8056825/f22195e7-ab64-4b6d-9eae-9379185ad638

**Comment by VitalInnovator** [comment]
fixed

**Comment by roszcz** [comment]
@VitalInnovator Dashboard works fine now, but I don't see any data in the history tab:

https://github.com/Nospoko/data-quality-platform/assets/8056825/a643382d-f940-4b58-96ee-5586665a1a3a

**Comment by VitalInnovator** [comment]
@roszcz This happens because we are using the names of non-existent datasets. I did not add a constraint by the dataset name on the `Dashboard` page since we were just starting to test this, and we only have 1 dataset in the `records` table. At the same time, such a constraint has already been added on the `History` page. Now, when selecting a dataset on the `History` page, filtering by the dataset name is already happening; Since you have a fictitious name, the history for you is empty. There are no records in the database with the dataset_name `foo`
If you create a dataset with a real name in the admin panel and select it on the history page, all historical data will be displayed for you.

I think that we can already add filtering by the dataset name on the dashboard page - even if it will work only with 1 dataset.

**Comment by roszcz** [comment]
I see, so for the history to work, I would need to create a dataset that has the same name as the "dataset_name" column in the records table, that was populated by the python code?

**Review by roszcz — APPROVED** [review]

**Pull request merged**
