### PR TITLE
QRS-46, Unify the records table for different data problems

### PR DESCRIPTION
**Pull request by VitalInnovator**
@roszcz I've added a DB update [Ticket](https://sacrebleu.atlassian.net/jira/software/projects/QRS/boards/6?selectedIssue=QRS-46) . The new migration will DELETE ALL data from the database for both 'record' and 'data_check(feedback)' tables.
I encountered an issue where Python is not populating the table for 'midi'.
Will you have time to Check?

### CODE REVIEW

**Comment by roszcz** [comment]
@VitalInnovator I'll take a look, but can you describe the issue, and give me some steps to reproduce?

**Comment by roszcz** [comment]
@VitalInnovator Any updates on this?

**Comment by VitalInnovator** [comment]
> @VitalInnovator Any updates on this?

I still have an issue 
image

**Comment by roszcz** [comment]
@VitalInnovator steps to reproduce would be much better than a screenshot :)

**Pull request closed without merging**
